apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: cbt-backend-hpa, namespace: cbt }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: cbt-backend }
  minReplicas: 6
  maxReplicas: 200
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 65 } }
    - type: Resource
      resource: { name: memory, target: { type: Utilization, averageUtilization: 75 } }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: cbt-frontend-hpa, namespace: cbt }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: cbt-frontend }
  minReplicas: 3
  maxReplicas: 40
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
